meta:
  title: Ansichtssachen
  description: Momente die mir im Laufe der Jahre vor die Linse gekommen sind.
  author:
    name: Kirsten Kluge
    email: photo@kirk.one,
    url: https://photo.kirk.one/